### ISSUE TITLE
Error running sample code

### ISSUE THREAD

**Issue by anqizhang1** [saudiwin/ordbetareg_pack#17]
Hello Dr. Kubinec, 

Thank you so much for the paper and package. It is very novel to me and I am learning from you. 

I run into an error running the sample code on [https://cran.r-project.org/web/packages/ordbetareg/vignettes/package_introduction.html](url) , I paste it here. When I set run_model to True, 

`
if(run_model) {
  ord_fit_mean <- ordbetareg(formula=therm ~ mo(education)*mo(income) +
                               (1|region), 
                       data=model_data,
                       control=list(adapt_delta=0.95),
                cores=1,chains=1,iter=500,
                refresh=0)
} else {
  data("ord_fit_mean")
}`

It shows error like this.  

![image](https://github.com/saudiwin/ordbetareg_pack/assets/97238937/1dc8d3e1-c241-4e17-99f5-8bc6953329ef)

Thank you very much.

**Comment by saudiwin** [comment]
hi @anqizhang1 - have you tried using/installing `cmdstanr`? See https://mc-stan.org/cmdstanr/. Then fit the model with the `backend="cmdstanr"` option. I think what you are seeing is an error with `rstan`, the default back-end that is a separate R package.

**Comment by lan-k** [comment]
I had this same error and solved it by installing rstan after ordbetareg

**Comment by saudiwin** [comment]
yes this isn't an error with ordbetareg, this is an issue with compiling models with rtools on Windows. @anqizhang1 can you try @lan-k solution above?
