### ISSUE TITLE
Syntax error with clean install of stack

### ISSUE THREAD

**Issue by atkissoncj** [saudiwin/ordbetareg_pack#20]
I got a new computer, so did a clean install of the Stan/rstan/cmdstanr stack. The model that I previously had working is no longer compiling. Maybe something wasn't done quite right in my install? Anyway, I receive the following error:

```
Syntax error in 'C:/Users/XXXX/AppData/Local/Temp/RtmpsHU8FO/model_42e711f2d392090e5892f6df506b3a25.stan', line 10, column 5 to column 6, parsing error:
   -------------------------------------------------
     8:     *   an integer sequence from start to end
     9:     */
    10:    int[] sequence(int start, int end) {
              ^
    11:      array[end - start + 1] int seq;
    12:      for (n in 1:num_elements(seq)) {
   -------------------------------------------------

An identifier is expected as a function name.

Error: Syntax error found! See the message above for more information.
```

My R version information is
```
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          3.3                              
year           2024                             
month          02                               
day            29                               
svn rev        86002                            
language       R                                
version.string R version 4.3.3 (2024-02-29 ucrt)
nickname       Angel Food Cake 
```

Do you need any other info?

Thanks!

**Comment by saudiwin** [comment]
Can you compile and run any other cmdstanr programs?

**Comment by atkissoncj** [comment]
Yes, I can. For example, I can compile and run the example model at  Getting
started with CmdStanR • cmdstanr (mc-stan.org)
<https://mc-stan.org/cmdstanr/articles/cmdstanr.html>

Curtis Atkisson

**Comment by saudiwin** [comment]
It's going to be tough for me to work on this unfortunately as I don't have a windows machine, only linux + Mac OS X.

**Comment by atkissoncj** [comment]
If you want to guide me as to what "work on this" means, I can do the
"working on this".

Curtis Atkisson

**Comment by saudiwin** [comment]
So I did some looking into it, and this is actually an issue with brms, not ordbetareg. It looks like if you update to the development version of brms the issue will be resolved. See thread here: 

https://discourse.mc-stan.org/t/problem-with-brms-multithreading-on-mac/33970/6

Closing issue as it does not pertain to ordbetareg directly (thankfully).

**Comment by atkissoncj** [comment]
Excellent!

Curtis Atkisson
