### ISSUE TITLE
Marginaleffects glmmTMB error

### ISSUE THREAD

**Issue by jgeller112** [saudiwin/ordbetareg_pack#26]
Hi, 

When I fit an ordered beta regression model with glmmTMB and use this model object in marginaleffects to extract predictions,  I run into an error

```
Error: The jacobian does not match the variance-covariance matrix.
```

I am using marginaleffects version 0.22.0.3

**Comment by saudiwin** [comment]
ah whoops sorry @jgeller112 I missed the key detail here about glmmTMB 😆 . I can't fix this, it ain't my package. sorry! we'll need to report this to marginaleffects and/or glmmTMB (probably the former).
