### ISSUE TITLE
Documentation of link functions

### ISSUE THREAD

**Issue by bgall** [saudiwin/ordbetareg_pack#4]
At various points in the documentation, it looks like the scale of $\phi$ is described as if its linear predictor is transformed with the **logit** link function. For example, see below. However, isn't $\phi$ modelled with the **log** link while $\mu$ uses the logit link?

![image](https://user-images.githubusercontent.com/16326193/179342641-c31a494d-0da0-4ca1-af54-767a461fe34a.png)

**Comment by saudiwin** [comment]
Yes you are correct, will update the documentation.
